apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: {{ .Values.Namespace }}
spec:
  version: 7.6.2
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
    - name: default
      count: 1
      config:
        node.master: true
        node.data: true
        node.ingest: true
        node.store.allow_mmap: false
        xpack.security.authc:
          anonymous:
            username: anonymous
            roles: superuser
            authz_exception: false
      podTemplate:
        spec:
          tolerations:
            - effect: "NoSchedule"
              key: "kubernetes.azure.com/scalesetpriority"
              operator: "Equal"
              value: "spot"
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 1
                  preference:
                    matchExpressions:
                      - key: kubernetes.azure.com/scalesetpriority
                        operator: In
                        values:
                          - spot
          initContainers:
            - name: install-plugins
              command:
                - sh
                - -c
                - bin/elasticsearch-plugin install https://github.com/OpenNMS/elasticsearch-drift-plugin/releases/download/v7.6.2/elasticsearch-drift-plugin-7.6.2.zip
              securityContext:
                privileged: true
          containers:
            - name: elasticsearch
              env:
                - name: ES_JAVA_OPTS
                  value: -Xms500m -Xmx500m
              resources:
                requests:
                  memory: 800Mi
                limits:
                  memory: 1.5Gi
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
            storageClassName: default