operator:
  namespace: opennms
  serviceName: opennms-operator
  image: opennms-operator:bleeding
  imagePullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 50Mi
customErrors:
  image: quay.io/kubernetes-ingress-controller/custom-error-pages-amd64:0.4
  debug: true