operator:
  namespace: opennms
  serviceName: opennms-operator
  image: opennms/operator:bleeding
  imagePullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 50Mi
  devMode: false
customErrors:
  image: quay.io/kubernetes-ingress-controller/custom-error-pages-amd64:0.4
  debug: true
serviceImages:
  auth: placeholder
  grafana: placeholder
  initContainer: placeholder
ssl:
  enabled: true
  issuer:
    issuerServer: https://acme-v02.api.letsencrypt.org/directory
    issuerUserEmail: email@address.com
  cert:
    hostname: "*.wildcard.domain.com"
  # Configure according to: https://cert-manager.io/docs/configuration/acme/dns01/
  solver: |
    cloudDNS:
      project: my-project
      serviceAccountSecretRef:
        name: prod-clouddns-svc-acct-secret
        key: service-account.json
nodeRestrictions: # will be applied to every pod in every instance deployed by the operator
  key: kubernetes.azure.com/scalesetpriority
  value: spot
