apiVersion: v1
kind: ConfigMap
metadata:
  name: stunnel-runtime
  namespace: {{ .Values.namespace }}
data:
  entry.sh: |-
    #!/bin/sh

    INTERVAL=2m
    CERT_FILE=/certificate/tls.crt

    LAST_CERT_MTIME=$(stat -L -c %Y ${CERT_FILE})
    /srv/stunnel.sh stunnel &
    while :
    do
        CERT_MTIME=$(stat -L -c %Y ${CERT_FILE})
        if [ ${CERT_MTIME} -gt ${LAST_CERT_MTIME} ]; then
            echo "Restarting: file ${CERT_FILE} changed"
            exit 0
        fi
        sleep ${INTERVAL}
    done

