apiVersion: v1
kind: Service
metadata:
  name: stunnel
  namespace: {{ .Values.Namespace }}
spec:
  selector:
    app: stunnel
  clusterIP: None
  ports:
    - name: activemq
      protocol: TCP
      port: 61616
  type: ClusterIP

