Namespace: opennms-instance
Host: local
TestDeploy: false
OpenNMS:
  Core:
    ServiceName: opennms-core
    Image: opennms/horizon-stream-core
    Resources:
      Limits:
        Cpu: 2
        Memory: 2Gi
      Requests:
        Cpu: 100m
        Memory: 1Gi
  API:
    ServiceName: opennms-rest-server
    Image: opennms/horizon-stream-rest-server
    Resources:
      Limits:
        Cpu: 100m
        Memory: 1Gi
      Requests:
        Cpu: 100m
        Memory: 1Gi
  UI:
    ServiceName: opennms-ui
    Image: opennms/horizon-stream-ui
    Resources:
      Limits:
        Cpu: 1
        Memory: 1Gi
      Requests:
        Cpu: 100m
        Memory: 1Gi
Postgres:
  ServiceName: postgres
  Image: postgres:13.3-alpine
  AdminPassword: notset
  KeycloakPassword: notset
  VolumeSize: 10Gi
Keycloak:
  ServiceName: keycloak
  Password: notset
Kafka: #TODO
  some: value
Grafana:
  Image: placeholder
Ingress:
  ControllerImage: k8s.gcr.io/ingress-nginx/controller:v1.1.0
  SecretJobImage: k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.1.1@sha256:64d8c73dca984af206adf9d6d7e46aa550362b1d7a01f3a0a91b20cc67868660
  WebhookPatchJobImage: k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.1.1@sha256:64d8c73dca984af206adf9d6d7e46aa550362b1d7a01f3a0a91b20cc67868660


