Namespace: opennms-instance
Host: localhost
OpenNMS:
  Image: opennms/horizon:bleeding
  VolumeSize: 500Mi
  SecurityGroup: 10001
  Resources:
    Limits:
      Cpu: 2
      Memory: 2Gi
    Requests:
      Cpu: 100m
      Memory: 1Gi
  InitContainerImage: placeholder
  Timeseries:
    Mode: default
    Host: postgresql
    Port: 5432
    ApiKey: placeholder
TLS:
  Enabled: false
  CertSecret: ssl-cert
Auth:
  Enabled: false
  Image: placeholder
  Port: 5000
  AdminPass: admin
  MinionPass: minion
  AllowedUsers: test@email.com
Postgres:
  Image: timescale/timescaledb:latest-pg12
  Password: password
  VolumeSize: 10Gi
Grafana:
  Image: placeholder
