Namespace: opennms-instance
Host: localhost
TestDeploy: false
OpenNMS:
  Image: opennms/horizon:bleeding
  VolumeSize: 500Mi
  SecurityGroup: 10001
  Resources:
    Limits:
      Cpu: 2
      Memory: 2Gi
    Requests:
      Cpu: 100m
      Memory: 1Gi
  InitContainerImage: placeholder
  Timeseries:
    Mode: default
    Host: postgresql
    Port: 5432
    ApiKey: placeholder
TLS:
  Enabled: false
  CertSecret: placeholder
Auth:
  Image: placeholder
  Port: 5000
  AdminPass: notset
  MinionPass: notset
  AllowedUsers: test@email.com
Postgres:
  Image: timescale/timescaledb:latest-pg12
  Password: notset
  VolumeSize: 10Gi
Grafana:
  Image: placeholder
Ingress:
  ControllerImage: k8s.gcr.io/ingress-nginx/controller:v1.1.0
  SecretJobImage: k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.1.1@sha256:64d8c73dca984af206adf9d6d7e46aa550362b1d7a01f3a0a91b20cc67868660
  WebhookPatchJobImage: k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.1.1@sha256:64d8c73dca984af206adf9d6d7e46aa550362b1d7a01f3a0a91b20cc67868660
Stunnel:
  Image: dweomer/stunnel:latest
NodeRestrictions: # will be applied to every pod in the instance
  Enabled: true
  Key: kubernetes.azure.com/scalesetpriority
  Value: spot

