apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opennms-ingress
  namespace: {{ .Values.Namespace }}
spec:
  rules:
    - host: {{ .Values.Host }}
      http:
        paths:
          {{ if .Values.Auth.Enabled }}
          - backend:
              service:
                name: auth-service
                port:
                  number: {{ .Values.Auth.Port }}
            path: /authz
            pathType: Prefix
          {{ end }}
          - backend:
              service:
                name: grafana
                port:
                  number: 3000
            path: /grafana
            pathType: Prefix
          - backend:
              service:
                name: opennms
                port:
                  number: 8980
            path: /
            pathType: Prefix
  {{ if .Values.TLS.Enabled }}
  tls:
    - hosts:
        -  {{.Values.Host }}
      secretName: {{ .Values.TLS.CertSecret }}
  {{ end }}