apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      ssl_reject_handshake "on";
  name: rejectipssl-ingress-{{ .Values.Namespace }}
  namespace: {{ .Values.Namespace }}
spec:
  ingressClassName: ingress-nginx-{{ .Values.Namespace }}
  rules:
  -  http:
      paths:
      - backend:
          service:
            name: opennms
            port:
              number: 8980
        path: /
        pathType: Prefix
