apiVersion: opennms.k8s.opennms.com/v1alpha1
kind: OpenNMS
metadata:
  name: local-instance
spec:
  allowedUsers: []
  host: localhost
  namespace: local-instance
  core:
    version: opennms/horizon-stream-core
  api:
    version: opennms/horizon-stream-api
  ui:
    version: opennms/horizon-stream-ui-dev
  postgres:
    version: postgres:13.3-alpine