apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.OpenNMS.UI.ServiceName }}
  name: {{ .Values.OpenNMS.UI.ServiceName }}
  namespace: {{ .Values.Namespace }}
spec:
  ports:
    - port: 3000
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.OpenNMS.UI.ServiceName }}
  type: NodePort