apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.OpenNMS.Core.ServiceName }}
  name: {{ .Values.OpenNMS.Core.ServiceName }}
  namespace: {{ .Values.Namespace }}
spec:
  ports:
    - port: 8101
      protocol: TCP
      name: ssh
    - port: 8181
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.OpenNMS.Core.ServiceName }}
  type: ClusterIP