apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etc
  namespace: {{ .Values.namespace }}
spec:
  accessModes: [ ReadWriteOnce ]
  resources:
    requests:
      storage: {{ .Values.opennms.volumeSize }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etc-overlay
  namespace: {{ .Values.namespace }}
spec:
  accessModes: [ ReadWriteOnce ]
  resources:
    requests:
      storage: {{ .Values.opennms.volumeSize }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deploy
  namespace: {{ .Values.namespace }}
spec:
  accessModes: [ ReadWriteOnce ]
  resources:
    requests:
      storage: {{ .Values.opennms.volumeSize }}