{{ if .Values.TLS.Enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: primary-{{ .Values.TLS.Cert.Name }}
  namespace: {{ .Values.Operator.Namespace }}
spec:
  secretName: {{ .Values.TLS.Cert.Name }}
  secretTemplate:
    annotations:
      replicator.v1.mittwald.de/replicate-to-matching: app.kubernetes.io/name=opennms
  commonName: '{{ .Values.TLS.Cert.Hostname }}'
  dnsNames:
    - '{{ .Values.TLS.Cert.Hostname }}'
  issuerRef:
    kind: ClusterIssuer
    name: cert-issuer
{{ end }}