{{ if .Values.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-issuer
  labels:
    version: 'v1'
  namespace: {{ .Values.Operator.Namespace }}
spec:
  acme:
    server: {{ .Values.TLS.Issuer.IssuerServer }}
    email: {{ .Values.TLS.Issuer.IssuerUserEmail }}
    privateKeySecretRef:
      name: cert-issuer
    solvers:
      - dns01:
{{ .Values.TLS.Solver | indent 10 }}
{{ end }}
