version: 2.1
executors:
  build-executor:
    docker:
      - image: cimg/go:1.17
    working_directory: /tmp

commands:
  dockerhub-login:
    description: "Connect to DockerHub"
    steps:
      - run:
          name: Login to DockerHub
          command: |
            if [ -n "${DOCKERHUB_LOGIN}" ]; then
              docker login -u ${DOCKERHUB_LOGIN} -p ${DOCKERHUB_PASS}
            else
              echo "WARNING: dockerhub login not found. Assuming this is a PR or other external branch build."
            fi

  save-image:
    description: "Save Docker Image to Workspace"
    steps:
      - run:
          command: |
            docker save -o /tmp/${CIRCLE_SHA1}-operator/operator.tar opennms/operator:$CIRCLE_SHA1
      - persist_to_workspace:
          root: ${CIRCLE_SHA1}-operator
          paths:
            - operator.tar

  load-image:
    description: "Load Docker Image from Workspace"
    steps:
      - attach_workspace:
          at: /tmp/${CIRCLE_SHA1}-operator
      - run:
          command: |
            docker load -i /tmp/${CIRCLE_SHA1}-operator/operator.tar

jobs:
  create-workspace:
    executor: build-executor
    steps:
      - run: mkdir -p ${CIRCLE_SHA1}-operator

  unit-tests:
    description: Unit Tests
    executor: build-executor
    steps:
      - checkout
      - run:
         command: make unit-test

  build-image:
    description: Build Docker Image
    executor: build-executor
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Docker build
          command: |
            docker build -t opennms/operator:${CIRCLE_SHA1} .
      - save-image

  sign-image:
    description: Sign Docker Image
    executor: build-executor
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - load-image
      - run:
          name: Sign Image
          command: |
            export DOCKER_CONTENT_TRUST=1
            export DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE="$DCT_REPO_OPERATOR_KEY_PASSPHRASE"
            KEY_FOLDER=$HOME/.docker/trust/private
            mkdir -p $KEY_FOLDER
            echo "$DCT_REPO_OPERATOR_KEY" | base64 -d > $KEY_FOLDER/$DCT_REPO_OPERATOR_KEY_NAME.key
            chmod 600 $KEY_FOLDER/*
            docker trust key load $KEY_FOLDER/$DCT_REPO_OPERATOR_KEY_NAME.key
            docker trust sign opennms/operator:$CIRCLE_SHA1
      - save-image

  push-image:
    description: Push Docker Image
    executor: build-executor
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - load-image
      - dockerhub-login
      - run:
          name: Docker push
          command: |
            docker tag opennms/operator:${CIRCLE_SHA1} opennms/operator:${CIRCLE_TAG}
            docker push opennms/operator:latest
            docker push opennms/operator:${CIRCLE_TAG}

workflows:
  build:
    jobs:
      - create-workspace

      - unit-tests:
          requires: [ create-workspace ]

      - build-image:
          requires: [ unit-tests ]

      - sign-image:
          requires: [ build-image ]
          context: docker-content-trust

      - push-image:
          requires: [ sign-image ]
          filters:
            branches: { only: "master" }
            tags: { only: "/(v[0-9].[0-9].[0-9])(-[a-zA-Z]+)?/" }
