version: 2.1
commands:
  dockerhub-login:
    description: "Connect to DockerHub"
    steps:
      - run:
          name: Login to DockerHub
          command: |
            if [ -n "${DOCKERHUB_LOGIN}" ]; then
              docker login -u ${DOCKERHUB_LOGIN} -p ${DOCKERHUB_PASS}
            else
              echo "WARNING: dockerhub login not found. Assuming this is a PR or other external branch build."
            fi

jobs:

  setup-dct:
    name: Setup Docker Content Trust
    docker:
      - image: circleci/golang:1.17
    context: docker-content-trust
    steps:
      - run:
          command: |
            echo "export DOCKER_CONTENT_TRUST=1" >> $BASH_ENV
            echo "export DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE=\"$DCT_REPO_OPERATOR_KEY_PASSPHRASE\"" >> $BASH_ENV

  sign-image:
    name: Sign Docker Image
    docker:
      - image: circleci/golang:1.17
    parameters:
      image-tag:
        type: string
    context: docker-content-trust
    steps:
      - run:
          command: |
            KEY_FOLDER=~/.docker/trust/private
            mkdir -p $KEY_FOLDER
            echo "$DCT_REPO_OPERATOR_KEY" | base64 -d > $KEY_FOLDER/$DCT_REPO_OPERATOR_KEY_NAME.key
            chmod 600 $KEY_FOLDER/*
            docker trust key load $KEY_FOLDER/$DCT_REPO_OPERATOR_KEY_NAME.key
            docker trust sign docker push opennms/operator:<< parameters.image-tag >>

workflows:
  build:
    jobs:
      - setup-dct

      - unit-tests:
          name: Unit Tests
          docker:
            - image: circleci/golang:1.17
          steps:
            - run:
                command: make unit-test

      - build-image:
          name: Build Docker Image
          requires: [ unit-tests ]
          docker:
            - image: circleci/golang:1.17
          steps:
            - checkout
            - run:
                name: Docker build
                command: |
                  docker build -t opennms/operator:${CIRCLE_SHA1} .

      - sign-image:
          image-tag: ${CIRCLE_SHA1}

      - push-image:
          name: Push Docker Image
          requires: [ sign-image ]
          docker:
            - image: circleci/golang:1.17
          filters:
            branches: { only: master }
            tags: { only: /(v[0-9].[0-9].[0-9])(-[a-zA-Z]+)?/ }
          steps:
            - dockerhub-login
            - run:
                name: Docker push
                command: |
                  docker tag opennms/operator:${CIRCLE_SHA1} opennms/operator:${CIRCLE_TAG}
                  docker push opennms/operator:latest
                  docker push opennms/operator:${CIRCLE_TAG}


