apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initial-sql
data:
  postgres.initial.script.sql: |
    CREATE USER opennms with password 'opennms';
    CREATE DATABASE horizon_stream;
    GRANT ALL ON DATABASE horizon_stream TO opennms;
  postgres.keycloak.initial.script.sql: |
    CREATE USER keycloak with password 'passw0rd';
    CREATE DATABASE keycloak;
    GRANT ALL ON DATABASE keycloak TO keycloak;