apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.Postgres.ServiceName }}
  name: {{ .Values.Postgres.ServiceName }}
  namespace: {{ .Values.Namespace }}
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: {{ .Values.Postgres.ServiceName }}