apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: {{ .Values.Namespace }}
stringData:
  adminUser: "postgres"
  adminPwd: "{{ .Values.Postgres.AdminPassword }}"
  keycloakUser: "keycloak"
  keycloakPwd: "{{ .Values.Postgres.KeycloakPassword }}"
type: Opaque