apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{.Values.Operator.serviceName }}-dependencies
  namespace: {{.Values.Operator.Namespace }}
rules: [
  {apiGroups: [""], resources: ["events"], verbs: ["get", "list", "watch", "update", "delete"]},
  {apiGroups: [""], resources: ["persistentvolumeclaims"], verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]},
  {apiGroups: ["agent.k8s.elastic.co"], resources: ["agents"], verbs: ["get", "list", "watch", "create", "update", "patch"]},
  {apiGroups: ["agent.k8s.elastic.co"], resources: ["agents/finalizers"], verbs: ["get", "list", "watch", "create", "update", "patch"]},
  {apiGroups: ["agent.k8s.elastic.co"], resources: ["agents/status"], verbs: ["get", "list", "watch", "create", "update", "patch"]},
  {apiGroups: ["apm.k8s.elastic.co"], resources: ["apmservers"], verbs: ["get", "list", "watch", "create", "update", "patch"]},
  {apiGroups: ["apm.k8s.elastic.co"], resources: ["apmservers/finalizers"], verbs: ["get", "list", "watch", "create", "update", "patch"]},
  {apiGroups: ["apm.k8s.elastic.co"], resources: ["apmservers/status"], verbs: ["get", "list", "watch", "create", "update", "patch"]},
  {apiGroups: ["apps"], resources: ["daemonsets"], verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] },
  {apiGroups: ["authorization.k8s.io"], resources: ["subjectaccessreviews"], verbs: ["create"]},
  {apiGroups: ["beat.k8s.elastic.co"], resources: ["beats"], verbs: ["get", "list", "watch", "create", "update", "patch"]},
  {apiGroups: ["beat.k8s.elastic.co"], resources: ["beats/finalizers"], verbs: ["get", "list", "watch", "create", "update", "patch"]},
  {apiGroups: ["beat.k8s.elastic.co"], resources: ["beats/status"], verbs: ["get", "list", "watch", "create", "update", "patch"]},
  {apiGroups: ["elasticsearch.k8s.elastic.co"], resources: ["elasticsearches"], verbs: ["get", "list", "watch", "create", "update", "patch"]},
  {apiGroups: ["elasticsearch.k8s.elastic.co"], resources: ["elasticsearches/finalizers"], verbs: ["get", "list", "watch", "create", "update", "patch"]},
  {apiGroups: ["elasticsearch.k8s.elastic.co"], resources: ["elasticsearches/status"], verbs: ["get", "list", "watch", "create", "update", "patch"]},
  {apiGroups: ["enterprisesearch.k8s.elastic.co"], resources: ["enterprisesearches"], verbs: ["get", "list", "watch", "create", "update", "patch"]},
  {apiGroups: ["enterprisesearch.k8s.elastic.co"], resources: ["enterprisesearches/finalizers"], verbs: ["get", "list", "watch", "create", "update", "patch"]},
  {apiGroups: ["enterprisesearch.k8s.elastic.co"], resources: ["enterprisesearches/status"], verbs: ["get", "list", "watch", "create", "update", "patch"]},
  {apiGroups: ["kibana.k8s.elastic.co"], resources: ["kibanas"], verbs: ["get", "list", "watch", "create", "update", "patch"]},
  {apiGroups: ["kibana.k8s.elastic.co"], resources: ["kibanas/finalizers"], verbs: ["get", "list", "watch", "create", "update", "patch"]},
  {apiGroups: ["kibana.k8s.elastic.co"], resources: ["kibanas/status"], verbs: ["get", "list", "watch", "create", "update", "patch"]},
  {apiGroups: ["maps.k8s.elastic.co"], resources: ["elasticmapsservers"], verbs: ["get", "list", "watch", "create", "update", "patch"]},
  {apiGroups: ["maps.k8s.elastic.co"], resources: ["elasticmapsservers/finalizers"], verbs: ["get", "list", "watch", "create", "update", "patch"]},
  {apiGroups: ["maps.k8s.elastic.co"], resources: ["elasticmapsservers/status"], verbs: ["get", "list", "watch", "create", "update", "patch"]},
  {apiGroups: ["policy"], resources: ["poddisruptionbudgets"], verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]},
  {apiGroups: ["storage.k8s.io"], resources: ["storageclasses"], verbs: ["get", "list", "watch"]},
  {apiGroups: ["agent.k8s.elastic.co"], resources: ["agents"], verbs: ["delete", "deletecollection"]},
  {apiGroups: ["apm.k8s.elastic.co"], resources: ["apmservers"], verbs: ["delete", "deletecollection"]},
  {apiGroups: ["beat.k8s.elastic.co"], resources: ["beats"], verbs: ["delete", "deletecollection"]}, 
  {apiGroups: ["elasticsearch.k8s.elastic.co"], resources: ["elasticsearches"], verbs: ["delete", "deletecollection"]}, 
  {apiGroups: ["enterprisesearch.k8s.elastic.co"], resources: ["enterprisesearches"], verbs: ["delete", "deletecollection"]},
  {apiGroups: ["kibana.k8s.elastic.co"], resources: ["kibanas"], verbs: ["delete", "deletecollection"]},
  {apiGroups: ["maps.k8s.elastic.co"], resources: ["elasticmapsservers"], verbs: ["delete", "deletecollection"]},
  {apiGroups: ["kafka.strimzi.io"], resources: ["kafkatopics"], verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]},
  {apiGroups: ["kafka.strimzi.io"], resources: ["kafkatopics/status"], verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]},
  {apiGroups: ["kafka.strimzi.io"], resources: ["kafkausers"], verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]},
  {apiGroups: ["kafka.strimzi.io"], resources: ["kafkausers/status"], verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]},
  {apiGroups: ["apps"], resources: ["deployments/scale"], verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]},
  {apiGroups: ["apps"], resources: ["deployments/status"], verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]},
  {apiGroups: ["apps"], resources: ["replicasets"], verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]},
  {apiGroups: ["build.openshift.io"], resources: ["buildconfigs"], verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]},
  {apiGroups: ["build.openshift.io"], resources: ["buildconfigs/instantiate"], verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]},
  {apiGroups: ["build.openshift.io"], resources: ["builds"], verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]},
  {apiGroups: ["core.strimzi.io"], resources: ["strimzipodsets"], verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]},
  {apiGroups: ["core.strimzi.io"], resources: ["strimzipodsets/status"], verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]},
  {apiGroups: ["extensions"], resources: ["deployments"], verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]},
  {apiGroups: ["extensions"], resources: ["deployments/scale"], verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]},
  {apiGroups: ["extensions"], resources: ["ingresses"], verbs: ["delete", "patch"]},
  {apiGroups: ["extensions"], resources: ["networkpolicies"], verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]},
  {apiGroups: ["extensions"], resources: ["replicasets"], verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]},
  {apiGroups: ["extensions"], resources: ["replicationcontrollers"], verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]},
  {apiGroups: ["kafka.strimzi.io"], resources: ["kafkabridges"], verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]},
  {apiGroups: ["kafka.strimzi.io"], resources: ["kafkabridges/status"], verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]},
  {apiGroups: ["kafka.strimzi.io"], resources: ["kafkaconnectors"], verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]},
  {apiGroups: ["kafka.strimzi.io"], resources: ["kafkaconnectors/status"], verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]},
  {apiGroups: ["kafka.strimzi.io"], resources: ["kafkaconnects"], verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]},
  {apiGroups: ["kafka.strimzi.io"], resources: ["kafkaconnects/status"], verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]},
  {apiGroups: ["kafka.strimzi.io"], resources: ["kafkamirrormaker2s"], verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]},
  {apiGroups: ["kafka.strimzi.io"], resources: ["kafkamirrormaker2s/status"], verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]},
  {apiGroups: ["kafka.strimzi.io"], resources: ["kafkamirrormakers"], verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]},
  {apiGroups: ["kafka.strimzi.io"], resources: ["kafkamirrormakers/status"], verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]},
  {apiGroups: ["kafka.strimzi.io"], resources: ["kafkarebalances"], verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]},
  {apiGroups: ["kafka.strimzi.io"], resources: ["kafkarebalances/status"], verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]},
  {apiGroups: ["kafka.strimzi.io"], resources: ["kafkas"], verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]},
  {apiGroups: ["kafka.strimzi.io"], resources: ["kafkas/status"], verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]},
  {apiGroups: ["networking.k8s.io"], resources: ["networkpolicies"], verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]},
  {apiGroups: ["route.openshift.io"], resources: ["routes"], verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]},
  {apiGroups: ["route.openshift.io"], resources: ["routes/custom-host"], verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]},
  {apiGroups: ["k8s.keycloak.org"], resources: ["keycloakrealmimports"], verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]},
  {apiGroups: ["k8s.keycloak.org"], resources: ["keycloakrealmimports/finalizers"], verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]},
  {apiGroups: ["k8s.keycloak.org"], resources: ["keycloakrealmimports/status"], verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]},
  {apiGroups: ["k8s.keycloak.org"], resources: ["keycloaks"], verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]},
  {apiGroups: ["k8s.keycloak.org"], resources: ["keycloaks/finalizers"], verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]},
  {apiGroups: ["k8s.keycloak.org"], resources: ["keycloaks/status"], verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]},
  {apiGroups: [""], resources: ["bindings"], verbs: ["get", "list", "watch"]},
  {apiGroups: [""], resources: ["limitranges"], verbs: ["get", "list", "watch"]},
  {apiGroups: [""], resources: ["namespaces/status"], verbs: ["get", "list", "watch"]},
  {apiGroups: [""], resources: ["persistentvolumeclaims/status"], verbs: ["get", "list", "watch"]},
  {apiGroups: [""], resources: ["pods/log"], verbs: ["get", "list", "watch"]},
  {apiGroups: [""], resources: ["pods/status"], verbs: ["get", "list", "watch"]},
  {apiGroups: [""], resources: ["replicationcontrollers"], verbs: ["get", "list", "watch"]},
  {apiGroups: [""], resources: ["replicationcontrollers/scale"], verbs: ["get", "list", "watch"]},
  {apiGroups: [""], resources: ["replicationcontrollers/status"], verbs: ["get", "list", "watch"]},
  {apiGroups: [""], resources: ["resourcequotas"], verbs: ["get", "list", "watch"]},
  {apiGroups: [""], resources: ["resourcequotas/status"], verbs: ["get", "list", "watch"]},
  {apiGroups: [""], resources: ["services/status"], verbs: ["get", "list", "watch"]},
  {apiGroups: ["apps"], resources: ["controllerrevisions"], verbs: ["get", "list", "watch"]},
  {apiGroups: ["apps"], resources: ["daemonsets/status"], verbs: ["get", "list", "watch"]},
  {apiGroups: ["apps"], resources: ["replicasets/scale"], verbs: ["get", "list", "watch"]},
  {apiGroups: ["apps"], resources: ["replicasets/status"], verbs: ["get", "list", "watch"]},
  {apiGroups: ["apps"], resources: ["statefulsets/scale"], verbs: ["get", "list", "watch"]},
  {apiGroups: ["apps"], resources: ["statefulsets/status"], verbs: ["get", "list", "watch"]},
  {apiGroups: ["autoscaling"], resources: ["horizontalpodautoscalers"], verbs: ["get", "list", "watch"]},
  {apiGroups: ["autoscaling"], resources: ["horizontalpodautoscalers/status"], verbs: ["get", "list", "watch"]},
  {apiGroups: ["batch"], resources: ["cronjobs"], verbs: ["get", "list", "watch"]},
  {apiGroups: ["batch"], resources: ["cronjobs/status"], verbs: ["get", "list", "watch"]},
  {apiGroups: ["batch"], resources: ["jobs/status"], verbs: ["get", "list", "watch"]},
  {apiGroups: ["discovery.k8s.io"], resources: ["endpointslices"], verbs: ["get", "list", "watch"]},
  {apiGroups: ["extensions"], resources: ["daemonsets"], verbs: ["get", "list", "watch"]},
  {apiGroups: ["extensions"], resources: ["daemonsets/status"], verbs: ["get", "list", "watch"]},
  {apiGroups: ["extensions"], resources: ["deployments/status"], verbs: ["get", "list", "watch"]},
  {apiGroups: ["extensions"], resources: ["replicasets/scale"], verbs: ["get", "list", "watch"]},
  {apiGroups: ["extensions"], resources: ["replicasets/status"], verbs: ["get", "list", "watch"]},
  {apiGroups: ["extensions"], resources: ["replicationcontrollers/scale"], verbs: ["get", "list", "watch"]},
  {apiGroups: ["policy"], resources: ["poddisruptionbudgets/status"], verbs: ["get", "list", "watch"]},
]

