apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ingress-nginx-{{ .Values.Namespace }}
  labels:
    app.kubernetes.io/name: ingress-nginx-{{ .Values.Namespace }}
    app.kubernetes.io/instance: ingress-nginx-{{ .Values.Namespace }}
    app.kubernetes.io/component: controller-{{ .Values.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress-nginx-{{ .Values.Namespace }}
subjects:
  - kind: ServiceAccount
    name: ingress-nginx
    namespace: {{ .Values.Namespace }}
