# Source: ingress-nginx/templates/controller-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: ingress-nginx-{{ .Values.Namespace }}
    app.kubernetes.io/instance: ingress-nginx-{{ .Values.Namespace }}
    app.kubernetes.io/component: controller-{{ .Values.Namespace }}
  name: ingress-nginx-{{ .Values.Namespace }}
  namespace: {{ .Values.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ingress-nginx-{{ .Values.Namespace }}
subjects:
  - kind: ServiceAccount
    name: ingress-nginx
    namespace: {{ .Values.Namespace }}
