apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: ingress-nginx-{{ .Values.Namespace }}
    app.kubernetes.io/instance: ingress-nginx-{{ .Values.Namespace }}
    app.kubernetes.io/component: controller-{{ .Values.Namespace }}
  name: ingress-nginx
  namespace: {{ .Values.Namespace }}
automountServiceAccountToken: true
