apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
    app.kubernetes.io/name: ingress-nginx-{{ .Values.Namespace }}
    app.kubernetes.io/instance: ingress-nginx-{{ .Values.Namespace }}
    app.kubernetes.io/component: controller-{{ .Values.Namespace }}
  name: ingress-nginx-{{ .Values.Namespace }}
  namespace: {{ .Values.Namespace }}
spec:
  controller: k8s.io/ingress-nginx-{{ .Values.Namespace }}