# Source: ingress-nginx/templates/controller-opennms-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: ingress-nginx-{{ .Values.Namespace }}
    app.kubernetes.io/instance: ingress-nginx-{{ .Values.Namespace }}
    app.kubernetes.io/component: controller-{{ .Values.Namespace }}
  name: ingress-nginx-controller
  namespace: {{ .Values.Namespace }}
data:
  custom-http-errors: 404,503,403,502
  allow-snippet-annotations: 'true'
