apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: {{ .Values.Namespace }}
  labels:
    app: auth-service
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - name: http
      port: {{ .Values.Auth.Port }}
      protocol: TCP

