apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: {{ .Values.Namespace }}
  labels:
    app: keycloak
spec:
  instances: 1
  externalAccess:
    enabled: True
    host: {{ .Values.Host }}