# Source: ingress-nginx/templates/admission-webhooks/job-patch/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingress-nginx-admission-{{ .Values.Namespace }}
  labels:
    app.kubernetes.io/name: ingress-nginx-admission-{{ .Values.Namespace }}
    app.kubernetes.io/instance: ingress-nginx-admission-{{ .Values.Namespace }}
    app.kubernetes.io/component: admission-webhook-{{ .Values.Namespace }}
rules:
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
    verbs:
      - get
      - update
