apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: ingress-nginx-{{ .Values.Namespace }}
    app.kubernetes.io/instance: ingress-nginx-{{ .Values.Namespace }}
    app.kubernetes.io/component: admission-webhook-{{ .Values.Namespace }}
  name: ingress-nginx-admission
  namespace: {{ .Values.Namespace }}
