apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-keycloak-initial-sql
data:
  postgres.keycloak.initial.script.sql: |
    CREATE USER keycloak with password 'passw0rd';
    CREATE DATABASE keycloak;
    GRANT ALL ON DATABASE keycloak TO keycloak;
