apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: opennms
  labels:
    app: sso
spec:
  keycloakCRName: my-keycloak
  realm:
    id: opennms
    realm: opennms
    enabled: true
    attributes:
      frontendUrl: "http://localhostkey"
    clients:
      - id: b67dfe9a-36c2-42bc-bd23-b380023d4238
        clientId: horizon-stream
        standardFlowEnabled: false
        enabled: true
        webOrigins:
          - "*"
        publicClient: true
        directAccessGrantsEnabled: true
        defaultClientScopes:
          - "web-origins"
          - "roles"
          - "profile"
          - "email"
        optionalClientScopes:
          - "address"
          - "phone"
          - "offline_access"
          - "microprofile-jwt"
    roles:
      realm:
      - id: 50e6b594-e01b-426b-873d-873f632355b4
        name: user
        composite: false
      - id: 76f0abc8-da17-4f57-8956-40cca624d62d
        name: admin
        composite: false
    users:
      - username: "admin"
        email: "admin@test.opennms.org"
        enabled: True
        emailVerified: False
        credentials:
          - type: "password"
            value: "admin"
        realmRoles:
          - "admin"
        clientRoles:
          account:
            - "manage-account"
            - "view-profile"
          realm-management:
            - "manage-users"
            - "view-users"
            - "query-users"
            - "create-client"
      - username: "user001"
        firstName: "User001"
        lastName: ""
        email: "user001@test.opennms.org"
        enabled: True
        emailVerified: False
        credentials:
          - type: "password"
            value: "passw0rd"
        realmRoles:
          - "user"
        clientRoles:
          account:
            - "manage-account"
            - "view-profile"
